import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#aeeecb",
        "on-surface": "#191c1e",
        "on-primary-fixed-variant": "#004a77",
        "surface-container": "#eceef0",
        "primary-fixed": "#cfe5ff",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#c2e8ff",
        "on-tertiary-container": "#92d9ff",
        "on-tertiary-fixed": "#001e2b",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#004d67",
        "primary-fixed-dim": "#98cbff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#296290",
        "on-primary-container": "#abd4ff",
        "secondary": "#2c694e",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#006080",
        "on-secondary-container": "#316e52",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#0e5138",
        "outline-variant": "#c1c7d1",
        "primary": "#00446f",
        "primary-container": "#225c8a",
        "secondary-fixed": "#b1f0ce",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#98cbff",
        "outline": "#717881",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#78d1fe",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#95d4b3",
        "on-surface-variant": "#414750",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#002114",
        "on-background": "#191c1e",
        "tertiary": "#004760",
        "on-primary-fixed": "#001d33",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
